FORMAT: 1A
HOST: https://toolstoremember.herokuapp.com/

# Sample da API

A Tools to remeber API demonstra como você utilizar de uma lista para armazenar as suas ferramentas consideradas mais importantes ou favoritas.


## Sobre 

Tools To Remember API tem como seu objetivo auxiliar na criação de uma lista de ferramentas informando seu título, website link, descrição e suas tags

O comportamento padrão é informar um erro  ao usuário se a ferramenta na qual ele está tentando inserir já existe, através da verificação do nome, informando-o também um alerta quando a ferramenta foi inserida a lista e quando foi excluída.


# Group Tools

## Tools [/tools]

### Criar ferramentas(tools) [POST]

+ Request Criar uma ferramenta

    + Headers 
          Accept: application/json
          Content-Type: application/json
    + Attributes (Tools)

+ Response 200 (application/json)

+ Response 201 (application/json)
    + Attributes (Error)

### Listar ferramentas(tools) [GET]

+ Response 200 (application/json)
    + Attributes (array[Tools])

+ Response 404 (application/json)
    + Attributes (Message)


### Excluir ferramentas(tools/{tool_id}) [DELETE]

+ Request Excluir uma ferramenta

+ Response 204

+ Response 404 
    + Attributes(Error)

## Mensagens [/tools]

  + Parameters
    + No parameters

## Visualizar tools [GET]

+ Response 200
    + Attributes (Tools)

+ Response 404
    + Attributes (Message)


## Mensagems [/tools/{tool_id}]

 + Parameters
    + tool_id: String - id da ferramenta

## Excluir Tools [DELETE]

+ Response 204

+ Response 404
  + Attriubutes(Error)


## Buscas de ferramentas [/tools?tag={title}]

+ Parameters
    + tool_title: title (String) - Título da ferramenta
    + tool_tag: tag (String) - Tags da ferramenta

## Listar ferramentas [GET]

+ Response 200 
    + Attributes (array[Tools])




